version: '3'

services:
  namenode:
    image: xiaobailong/hadoop_in_docker_single:3.0.3
    hostname: namenode
    networks:
      - ones_cloud
    expose:
      - 50070
      - 50090
      - 8020
      - 9000
    ports:
      - 50070:50070
    volumes:
      - /data/docker/data/hadoop/dfs/namenode:/data/hadoop/dfs/namenode

  datanode0:
    image: xiaobailong/hadoop_in_docker_single:3.0.3
    command: [
      "hdfs",
      "datanode",
      "-fs", "hdfs://namenode:9000",
      "-Ddfs.datanode.data.dir=/data/hadoop/dfs/datanode",
      "-Ddfs.permissions.enabled=false"
    ]
    hostname: datanode0
    networks:
      - ones_cloud
    expose:
      - 50010
      - 50020
      - 50075
    volumes:
      - /data/docker/data/hadoop/dfs/datanode/data1:/data/hadoop/dfs/datanode

  datanode1:
    image: xiaobailong/hadoop_in_docker_single:3.0.3
    command: [
      "hdfs",
      "datanode",
      "-fs", "hdfs://namenode:9000",
      "-Ddfs.datanode.data.dir=/data/hadoop/dfs/datanode",
      "-Ddfs.permissions.enabled=false"
    ]
    hostname: datanode1
    networks:
      - ones_cloud
    expose:
      - 50010
      - 50020
      - 50075
    volumes:
      - /data/docker/data/hadoop/dfs/datanode/data2:/data/hadoop/dfs/datanode

networks:
  ones_cloud:
    # Use a custom driver
    driver: bridge
